import { stageIds, type WorkflowPack } from '../engine/types';

const policy = { id: 'service-policy', type: 'policy' as const, title: 'Field service policy', sender: 'Operations', receivedAt: '2026-09-18 08:00 GST', fields: { Safety: 'Stop use and escalate immediately', Warranty: 'Parts covered for 12 months', Reschedule: 'One free change with 24 hours notice' }, body: 'Synthetic policy. Safety events always override normal routing and require human escalation.' };
export const customerOperationsPack: WorkflowPack = {
  id: 'customer-operations', label: 'Customer Operations', eyebrow: 'Workflow pack', featured: false, stages: stageIds,
  description: 'Classify requests, ground the resolution in policy, and prepare the next operational action.',
  scenarios: [
    { id: 'request-triage', label: 'Request triage', kind: 'happy', summary: 'Route three customer requests using one supplied service policy.', sourceRecords: [policy,
      { id: 'msg-reschedule', type: 'customer-message', title: 'Visit reschedule', sender: 'Atlas Kitchens', receivedAt: '2026-09-18 09:20 GST', fields: { Channel: 'Email', Notice: '48 hours' }, body: 'Synthetic message. Please move Tuesday’s maintenance visit to Thursday.' },
      { id: 'msg-warranty', type: 'customer-message', title: 'Warranty question', sender: 'Blue Harbor Café', receivedAt: '2026-09-18 09:42 GST', fields: { Channel: 'Form', Purchase: '8 months ago' }, body: 'Synthetic message. A covered pump has failed and the customer asks whether replacement parts are included.' },
      { id: 'msg-safety', type: 'customer-message', title: 'Burning smell from unit', sender: 'Crescent Bakery', receivedAt: '2026-09-18 09:51 GST', fields: { Channel: 'WhatsApp', Severity: 'Potential safety issue' }, body: 'Synthetic message. The unit is making noise and smells like burning.' }],
      stageSummaries: { intake: 'Received three synthetic requests and one service policy.', understand: 'Classified reschedule, warranty, and safety intents.', evaluate: 'Applied service rules and prioritized the safety event.', explain: 'Prepared grounded resolutions and an urgent escalation.' },
      decision: { recommendation: 'Approve the reschedule, open a warranty case, and escalate the safety request immediately.', confidence: 'high', rationale: ['The reschedule meets the 24-hour notice rule.', 'The pump is within the 12-month parts warranty.', 'A burning smell triggers mandatory stop-use escalation.'], evidence: [{ sourceId: 'service-policy', label: 'Service policy', excerpt: 'Safety: stop use and escalate immediately.' }, { sourceId: 'msg-reschedule', label: 'Reschedule request', excerpt: 'Requested 48 hours before the planned visit.' }, { sourceId: 'msg-warranty', label: 'Warranty request', excerpt: 'Purchase recorded eight months ago.' }, { sourceId: 'msg-safety', label: 'Safety request', excerpt: 'Unit smells like burning.' }], policyChecks: [{ id: 'safety', label: 'Safety override', result: 'warn', detail: 'Urgent human escalation is required.' }, { id: 'warranty', label: 'Warranty window', result: 'pass', detail: 'Eight months is within the 12-month parts coverage.' }, { id: 'reschedule', label: 'Notice period', result: 'pass', detail: '48 hours exceeds the 24-hour requirement.' }], missingInformation: [] }, preparedAction: { title: 'Triage actions', destination: 'Customer operations queue', body: 'Confirm the reschedule, open warranty case W-208, and place the safety request in the urgent escalation queue.' } },
    { id: 'policy-conflict', label: 'Policy conflict', kind: 'exception', summary: 'A warranty claim has conflicting purchase dates.', sourceRecords: [policy, { id: 'msg-conflict', type: 'customer-message', title: 'Warranty replacement', sender: 'Harbor Foods', receivedAt: '2026-09-19 11:03 GST', fields: { 'Customer claim': '10 months ago', 'Account record': '14 months ago' }, body: 'Synthetic message. Customer requests a covered replacement, but supplied dates conflict.' }], stageSummaries: { intake: 'Received the request and service policy.', understand: 'Detected conflicting purchase dates.', evaluate: 'Paused warranty resolution because eligibility cannot be established.', explain: 'Prepared a proof-of-purchase request and escalation.' }, decision: { recommendation: 'Request proof of purchase and escalate the conflict.', confidence: 'medium', rationale: ['The customer claim is inside warranty, but the account record is outside it.'], evidence: [{ sourceId: 'msg-conflict', label: 'Warranty request', excerpt: 'Customer says 10 months; account says 14 months.' }, { sourceId: 'service-policy', label: 'Service policy', excerpt: 'Parts covered for 12 months.' }], policyChecks: [{ id: 'warranty-date', label: 'Warranty eligibility', result: 'fail', detail: 'Conflicting dates prevent a reliable eligibility decision.' }], missingInformation: ['Dated proof of purchase'] }, preparedAction: { title: 'Warranty clarification', destination: 'Customer operations manager', body: 'Request dated proof of purchase and hold the replacement decision until the conflict is resolved.' } },
  ],
};
