import { stageIds, type WorkflowPack } from '../engine/types';

const role = { id: 'role-ops', type: 'request' as const, title: 'Automation Operations Lead', sender: 'People Operations', receivedAt: '2026-09-18 08:30 GST', fields: { Required: '5+ years operations; workflow automation; stakeholder delivery', Preferred: 'n8n; API integrations; production monitoring' }, body: 'Synthetic role brief. Evaluate only job-related evidence supplied in each CV.' };
const policy = { id: 'hiring-policy', type: 'policy' as const, title: 'Shortlisting policy', sender: 'People Operations', receivedAt: '2026-09-18 08:31 GST', fields: { Rule: 'Required criteria must be evidenced', Protected: 'Never infer protected attributes' }, body: 'Synthetic policy. Cite CV evidence, flag unknowns, and leave final decisions to a human recruiter.' };
export const recruitmentPack: WorkflowPack = {
  id: 'recruitment', label: 'Recruitment', eyebrow: 'Workflow pack', featured: false, stages: stageIds,
  description: 'Evaluate candidates against stated criteria, cite evidence, and prepare a human-owned shortlist.',
  scenarios: [
    { id: 'candidate-shortlist', label: 'Candidate shortlist', kind: 'happy', summary: 'Review three synthetic CVs against one role brief.',
      sourceRecords: [role, policy,
        { id: 'cv-salma', type: 'cv', title: 'Salma N. CV', sender: 'Applicant', receivedAt: '2026-09-18 09:14 GST', fields: { Experience: '7 years operations', Automation: 'n8n, APIs, monitoring', Delivery: 'Led 12 cross-functional launches' }, body: 'Synthetic CV. Built monitored workflows, handled incidents, and led operations stakeholders.' },
        { id: 'cv-omar', type: 'cv', title: 'Omar R. CV', sender: 'Applicant', receivedAt: '2026-09-18 09:26 GST', fields: { Experience: '6 years operations', Automation: 'Zapier, Make', Delivery: 'Managed regional process redesign' }, body: 'Synthetic CV. Strong process ownership; no production monitoring example supplied.' },
        { id: 'cv-lina', type: 'cv', title: 'Lina K. CV', sender: 'Applicant', receivedAt: '2026-09-18 09:41 GST', fields: { Experience: '3 years operations', Automation: 'Python scripts', Delivery: 'Individual projects' }, body: 'Synthetic CV. Technical promise but does not evidence five years or stakeholder leadership.' }],
      stageSummaries: { intake: 'Received one role brief, policy, and three synthetic CVs.', understand: 'Mapped each CV to required and preferred criteria.', evaluate: 'Separated evidenced fit from missing information without inferring personal attributes.', explain: 'Prepared a ranked shortlist with citations for recruiter review.' },
      decision: { recommendation: 'Shortlist Salma N. and review Omar R.; do not shortlist Lina K. for this role.', confidence: 'high', rationale: ['Salma directly evidences every required criterion.', 'Omar meets core experience but lacks monitoring evidence.', 'Lina does not evidence the minimum experience or stakeholder leadership.'], evidence: [{ sourceId: 'cv-salma', label: 'Salma CV', excerpt: '7 years, n8n and APIs, 12 cross-functional launches.' }, { sourceId: 'role-ops', label: 'Role brief', excerpt: '5+ years, automation, stakeholder delivery.' }], policyChecks: [{ id: 'required', label: 'Required criteria', result: 'pass', detail: 'At least one candidate evidences all required criteria.' }, { id: 'fairness', label: 'Job-related evidence only', result: 'pass', detail: 'No protected attributes were evaluated or inferred.' }], missingInformation: ['Production monitoring example from Omar R.'] },
      preparedAction: { title: 'Shortlist for recruiter review', destination: 'Recruiter queue', body: 'Advance Salma N.; request monitoring evidence from Omar R.; close Lina K. for this role after human confirmation.' } },
    { id: 'insufficient-evidence', label: 'Insufficient evidence', kind: 'exception', summary: 'A strong claim lacks enough evidence for automatic shortlisting.', sourceRecords: [role, policy, { id: 'cv-nour', type: 'cv', title: 'Nour A. CV', sender: 'Applicant', receivedAt: '2026-09-19 10:02 GST', fields: { Experience: 'Operations leader', Automation: 'Advanced', Delivery: 'Cross-functional' }, body: 'Synthetic CV. Claims relevant expertise but gives no dates, systems, project examples, or outcomes.' }], stageSummaries: { intake: 'Received role, policy, and one sparse CV.', understand: 'Mapped claims but found no verifiable examples.', evaluate: 'Refused to convert unsupported claims into a positive shortlist decision.', explain: 'Prepared a targeted evidence request.' }, decision: { recommendation: 'Return for clarification before shortlisting.', confidence: 'medium', rationale: ['The CV claims fit but does not evidence years, tools, or delivery examples.'], evidence: [{ sourceId: 'cv-nour', label: 'Nour CV', excerpt: 'Claims advanced automation without supporting examples.' }], policyChecks: [{ id: 'evidence', label: 'Evidence threshold', result: 'fail', detail: 'Required criteria are asserted but not evidenced.' }], missingInformation: ['Employment dates', 'Named automation systems', 'One stakeholder delivery example'] }, preparedAction: { title: 'Evidence request', destination: 'Recruiter queue', body: 'Request employment dates, automation examples, and one stakeholder delivery case before review resumes.' } },
  ],
};
